[project]
name = "mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask==3.0.0",
    "kagglehub==0.2.5",
    "numpy==1.26.2",
    "pandas==2.1.4",
    "scikit-learn==1.3.2",
    "tensorflow>=2.18.1",
]
